name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build pages
        run: pnpm run build
        env:
          GITALK_CLIENT_ID: ${{ secrets.GITALK_CLIENT_ID }}
          GITALK_SECRET: ${{ secrets.GITALK_SECRET }}
          GITALK_REPO: ${{ vars.GITALK_REPO }}
          GITALK_OWNER: ${{ vars.GITALK_OWNER }}
          GITALK_ADMINS: ${{ vars.GITALK_ADMINS }}
          GITALK_CREATE_ISSUE_TOKEN: ${{ secrets.GITALK_CREATE_ISSUE_TOKEN }}

      - name: Deploy with gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
